package main

const (
	// app
	APP_ID       = "github.com.caticat.go_git_notebook_gui"
	WINDOW_TITLE = "PNoteBook"
	APP_AUTHOR   = "Pan J"
	APP_VER      = "v0.0.1"
	APP_CFG_KEY  = "config"

	// config
	APP_CFG_VALUE_DEFAULT = `
{
	"repository" : "",
	"local" : "./data",
	"username" : "",
	"password" : "",
	"authorname" : "",
	"authoremail" : "",
	"loglevel" : 1
}
`

	// gui
	GUI_WINDOW_INIT_SIZE_W         = 1000 // 窗口初始大小W
	GUI_WINDOW_INIT_SIZE_H         = 700  // 窗口初始大小H
	GUI_HOME_OFFSET                = 0.3  // 初始主界面分隔比率
	GUI_DIALOG_AUTOCLOSE_WAIT_TIME = 300  // 弹窗自动关闭事件 毫秒

	// plog
	PLOG_MAX_SIZE = 1 << 20 // 日志数据量
	PLOG_CHAN_LEN = 100     // 数据管道长度

	// notebook
	NOTEBOOK_PERM_FILE        = 0666      // 文件权限
	NOTEBOOK_PERM_FOLDER      = 0755      // 文件夹权限
	NOTEBOOK_TMP_FILE_NAME    = "tmp.txt" // 空项目占位文件,因为go-git无法清空项目提交的问题,需要至少一个文件保证可以提交清空操作
	NOTEBOOK_TMP_FILE_CONTENT = "this file is generated by " + WINDOW_TITLE + " for a go-git bug to commit empty workspace\nyou can treat this file as an regular file\nand do whatever you want."
)
